/**
 * The cities SellWant covers: the largest US cities, in population order.
 *
 * A fixed list rather than a geocoder. A Places API would cost money and put a
 * key in the client to answer a question this list already answers, and letting
 * the list grow from whatever people type is what produced a listing whose
 * location was "halloween" -- a filter is only worth having when every value in
 * the column is one the filter knows about.
 *
 * Population order, not alphabetical, because this is a list people scan and
 * the answer is usually near the top. Search matches anywhere in the name, so
 * ordering never hides a city -- "wor" still finds Fort Worth.
 *
 * Generated from cities.csv. Fifteen rows of that file were dropped as repeats:
 * names like Columbus, Kansas City and Springfield appear more than once
 * because they are different cities in different states, and the file carries
 * no state column to tell them apart. Adding states later means adding a field,
 * not reordering this one.
 */
export const CITIES = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Philadelphia',
  'Phoenix',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Indianapolis',
  'Jacksonville',
  'San Francisco',
  'Columbus',
  'Charlotte',
  'Fort Worth',
  'Detroit',
  'El Paso',
  'Memphis',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'Nashville-Davidson',
  'Baltimore',
  'Oklahoma City',
  'Louisville/Jefferson County',
  'Portland',
  'Las Vegas',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Long Beach',
  'Kansas City',
  'Mesa',
  'Virginia Beach',
  'Atlanta',
  'Colorado Springs',
  'Omaha',
  'Raleigh',
  'Miami',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Cleveland',
  'Wichita',
  'Arlington',
  'New Orleans',
  'Bakersfield',
  'Tampa',
  'Honolulu',
  'Aurora',
  'Anaheim',
  'Santa Ana',
  'St. Louis',
  'Riverside',
  'Corpus Christi',
  'Lexington-Fayette',
  'Pittsburgh',
  'Anchorage',
  'Stockton',
  'Cincinnati',
  'St. Paul',
  'Toledo',
  'Greensboro',
  'Newark',
  'Plano',
  'Henderson',
  'Lincoln',
  'Buffalo',
  'Jersey City',
  'Chula Vista',
  'Fort Wayne',
  'Orlando',
  'St. Petersburg',
  'Chandler',
  'Laredo',
  'Norfolk',
  'Durham',
  'Madison',
  'Lubbock',
  'Irvine',
  'Winston-Salem',
  'Glendale',
  'Garland',
  'Hialeah',
  'Reno',
  'Chesapeake',
  'Gilbert',
  'Baton Rouge',
  'Irving',
  'Scottsdale',
  'North Las Vegas',
  'Fremont',
  'Boise City',
  'Richmond',
  'San Bernardino',
  'Birmingham',
  'Spokane',
  'Rochester',
  'Des Moines',
  'Modesto',
  'Fayetteville',
  'Tacoma',
  'Oxnard',
  'Fontana',
  'Montgomery',
  'Moreno Valley',
  'Shreveport',
  'Yonkers',
  'Akron',
  'Huntington Beach',
  'Little Rock',
  'Augusta-Richmond County',
  'Amarillo',
  'Mobile',
  'Grand Rapids',
  'Salt Lake City',
  'Tallahassee',
  'Huntsville',
  'Grand Prairie',
  'Knoxville',
  'Worcester',
  'Newport News',
  'Brownsville',
  'Overland Park',
  'Santa Clarita',
  'Providence',
  'Garden Grove',
  'Chattanooga',
  'Oceanside',
  'Jackson',
  'Fort Lauderdale',
  'Santa Rosa',
  'Rancho Cucamonga',
  'Port St. Lucie',
  'Tempe',
  'Ontario',
  'Vancouver',
  'Cape Coral',
  'Sioux Falls',
  'Springfield',
  'Peoria',
  'Pembroke Pines',
  'Elk Grove',
  'Salem',
  'Lancaster',
  'Corona',
  'Eugene',
  'Palmdale',
  'Salinas',
  'Pasadena',
  'Fort Collins',
  'Hayward',
  'Pomona',
  'Cary',
  'Rockford',
  'Alexandria',
  'Escondido',
  'McKinney',
  'Joliet',
  'Sunnyvale',
  'Torrance',
  'Bridgeport',
  'Lakewood',
  'Hollywood',
  'Paterson',
  'Naperville',
  'Syracuse',
  'Mesquite',
  'Dayton',
  'Savannah',
  'Clarksville',
  'Orange',
  'Fullerton',
  'Killeen',
  'Frisco',
  'Hampton',
  'McAllen',
  'Warren',
  'Bellevue',
  'West Valley City',
  'Columbia',
  'Olathe',
  'Sterling Heights',
  'New Haven',
  'Miramar',
  'Waco',
  'Thousand Oaks',
  'Cedar Rapids',
  'Charleston',
  'Visalia',
  'Topeka',
  'Elizabeth',
  'Gainesville',
  'Thornton',
  'Roseville',
  'Carrollton',
  'Coral Springs',
  'Stamford',
  'Simi Valley',
  'Concord',
  'Hartford',
  'Kent',
  'Lafayette',
  'Midland',
  'Surprise',
  'Denton',
  'Victorville',
  'Evansville',
  'Santa Clara',
  'Abilene',
  'Athens-Clarke County',
  'Vallejo',
  'Allentown',
  'Norman',
  'Beaumont',
  'Independence',
  'Murfreesboro',
  'Ann Arbor',
  'Berkeley',
  'Provo',
  'El Monte',
  'Lansing',
  'Fargo',
  'Downey',
  'Costa Mesa',
  'Wilmington',
  'Arvada',
  'Inglewood',
  'Miami Gardens',
  'Carlsbad',
  'Westminster',
  'Odessa',
  'Manchester',
  'Elgin',
  'West Jordan',
  'Round Rock',
  'Clearwater',
  'Waterbury',
  'Gresham',
  'Fairfield',
  'Billings',
  'Lowell',
  'San Buenaventura (Ventura)',
  'Pueblo',
  'High Point',
  'West Covina',
  'Murrieta',
  'Cambridge',
  'Antioch',
  'Temecula',
  'Norwalk',
  'Centennial',
  'Everett',
  'Palm Bay',
  'Wichita Falls',
  'Green Bay',
  'Daly City',
  'Burbank',
  'Richardson',
  'Pompano Beach',
  'North Charleston',
  'Broken Arrow',
  'Boulder',
  'West Palm Beach',
  'Santa Maria',
  'El Cajon',
  'Davenport',
  'Rialto',
  'Las Cruces',
  'San Mateo',
  'Lewisville',
  'South Bend',
  'Lakeland',
  'Erie',
  'Tyler',
  'Pearland',
  'College Station',
  'Kenosha',
  'Sandy Springs',
  'Clovis',
  'Flint',
  'Roanoke',
  'Albany',
  'Jurupa Valley',
  'Compton',
  'San Angelo',
  'Hillsboro',
  'Lawton',
  'Renton',
  'Vista',
  'Davie',
  'Greeley',
  'Mission Viejo',
  'Portsmouth',
  'Dearborn',
  'South Gate',
  'Tuscaloosa',
  'Livonia',
  'New Bedford',
  'Vacaville',
  'Brockton',
  'Roswell',
  'Beaverton',
  'Quincy',
  'Sparks',
  'Yakima',
  'Lee\'s Summit',
  'Federal Way',
  'Carson',
  'Santa Monica',
  'Hesperia',
  'Allen',
  'Rio Rancho',
  'Yuma',
  'Orem',
  'Lynn',
  'Redding',
  'Spokane Valley',
  'Miami Beach',
  'League City',
  'Lawrence',
  'Santa Barbara',
  'Plantation',
  'Sandy',
  'Sunrise',
  'Macon',
  'Longmont',
  'Boca Raton',
  'San Marcos',
  'Greenville',
  'Waukegan',
  'Fall River',
  'Chico',
  'Newton',
  'San Leandro',
  'Reading',
  'Fort Smith',
  'Newport Beach',
  'Asheville',
  'Nashua',
  'Edmond',
  'Whittier',
  'Nampa',
  'Bloomington',
  'Deltona',
  'Hawthorne',
  'Duluth',
  'Carmel',
  'Suffolk',
  'Clifton',
  'Citrus Heights',
  'Livermore',
  'Tracy',
  'Alhambra',
  'Kirkland',
  'Trenton',
  'Ogden',
  'Hoover',
  'Cicero',
  'Fishers',
  'Sugar Land',
  'Danbury',
  'Meridian',
  'Indio',
  'Menifee',
  'Champaign',
  'Buena Park',
  'Troy',
  'O\'Fallon',
  'Johns Creek',
  'Bellingham',
  'Westland',
  'Sioux City',
  'Warwick',
  'Hemet',
] as const;

export type City = (typeof CITIES)[number];

/** How many options to show before someone starts typing. */
const BROWSE_LIMIT = 8;

const canon = (s: string) => s.trim().toLowerCase().replace(/\s+/g, ' ');

/**
 * The canonical city for a stored value, or null.
 *
 * Listings written before cities existed hold venues ("Sig Ep house") and worse
 * ("halloween"), so every read has to cope with a value that is not a city.
 * Returning null rather than guessing keeps those out of city filters instead
 * of filing them under whichever city looks closest.
 */
export function toCity(value: string | null | undefined): City | null {
  if (!value) return null;
  const q = canon(value);
  return CITIES.find((c) => canon(c) === q) ?? null;
}

/**
 * Cities matching what has been typed, best first.
 *
 * Capped, and capped hardest when nothing is typed: 380 options in an
 * open dropdown is a wall, not a choice. Prefix matches rank above interior
 * ones because someone typing a city name is typing its start.
 */
export function matchCities(query: string, limit = 40): City[] {
  const q = canon(query);
  if (!q) return CITIES.slice(0, BROWSE_LIMIT) as unknown as City[];
  const starts: City[] = [];
  const contains: City[] = [];
  for (const c of CITIES) {
    const k = canon(c);
    if (k.startsWith(q)) starts.push(c);
    else if (k.includes(q)) contains.push(c);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
